// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// sd
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDCh9kYPOSZ6-K3FYYJ2jlK4QS9-KqEvk',
    appId: '1:246944187312:android:9e709ec88c5d1a41994c75',
    messagingSenderId: '246944187312',
    projectId: 'Difwabite',
    storageBucket: 'Difwabite.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9_QnO0cYAa53Kw3VFqhDa3ZXjCHvovlw',
    appId: '1:246944187312:web:4b9be407cad8648e994c75',
    messagingSenderId: '246944187312',
    projectId: 'Difwabite',
    authDomain: 'Difwabite.firebaseapp.com',
    storageBucket: 'Difwabite.firebasestorage.app',
    measurementId: 'G-C5ZK3Z8F1P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3gkH97rVWWPptU5IX4PCXV7WjRH6U2U0',
    appId: '1:246944187312:ios:fe1480df51616526994c75',
    messagingSenderId: '246944187312',
    projectId: 'Difwabite',
    storageBucket: 'Difwabite.firebasestorage.app',
    iosBundleId: 'com.example.liciusApplication',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3gkH97rVWWPptU5IX4PCXV7WjRH6U2U0',
    appId: '1:246944187312:ios:1c0948f6a18630dc994c75',
    messagingSenderId: '246944187312',
    projectId: 'Difwabite',
    storageBucket: 'Difwabite.firebasestorage.app',
    iosBundleId: 'com.Difwabite.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9_QnO0cYAa53Kw3VFqhDa3ZXjCHvovlw',
    appId: '1:246944187312:web:5900891e0b7f1eb7994c75',
    messagingSenderId: '246944187312',
    projectId: 'Difwabite',
    authDomain: 'Difwabite.firebaseapp.com',
    storageBucket: 'Difwabite.firebasestorage.app',
    measurementId: 'G-Q2Q4D4YXED',
  );
}
