// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkIEDcdXJgHvjc9PWgu1NB8EfPTr4EmU',
    appId: '1:318884564100:web:ea8cc6c6a23be63b0586d1',
    messagingSenderId: '318884564100',
    projectId: 'difwa-water',
    authDomain: 'difwa-water.firebaseapp.com',
    storageBucket: 'difwa-water.firebasestorage.app',
    measurementId: 'G-NQBLS027XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42MMuG3Srmh68RxlnT5tJd90_tTClAsc',
    appId: '1:318884564100:android:b533204c5a0d62aa0586d1',
    messagingSenderId: '318884564100',
    projectId: 'difwa-water',
    storageBucket: 'difwa-water.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChRrBg6dDlq5mGZRq4WcmOr2V2JRveowQ',
    appId: '1:318884564100:ios:f5cff5ff42c1cece0586d1',
    messagingSenderId: '318884564100',
    projectId: 'difwa-water',
    storageBucket: 'difwa-water.firebasestorage.app',
    iosBundleId: 'com.difmo.difwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChRrBg6dDlq5mGZRq4WcmOr2V2JRveowQ',
    appId: '1:318884564100:ios:215bb2797a1c57330586d1',
    messagingSenderId: '318884564100',
    projectId: 'difwa-water',
    storageBucket: 'difwa-water.firebasestorage.app',
    iosBundleId: 'com.example.liciusApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBkIEDcdXJgHvjc9PWgu1NB8EfPTr4EmU',
    appId: '1:318884564100:web:3d9df80a6e4521060586d1',
    messagingSenderId: '318884564100',
    projectId: 'difwa-water',
    authDomain: 'difwa-water.firebaseapp.com',
    storageBucket: 'difwa-water.firebasestorage.app',
    measurementId: 'G-DZ6ZQRLNQN',
  );
}
